CREATE DATABASE customer_shopping_analysis
USE customer_shopping_analysis

select * from customer

-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from customer
where discount_applied='Yes' AND purchase_amount>=(select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(AVG(review_rating),2) as rating
from customer
group by item_purchased
order by rating desc limit 5

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,avg(purchase_amount) as amount
from customer
group by shipping_type
having shipping_type in ('Standard','Express')

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_customers,AVG(purchase_amount) as Average_puchase_amount,sum(purchase_amount) as Total_Revenue
from customer
group by subscription_status
order by Average_puchase_amount,Total_Revenue desc

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with total_purchased as (
select customer_id,previous_purchases,
CASE WHEN previous_purchases=1 THEN 'New'
when previous_purchases between 2 and 10 then 'Returning'
ELSE 'Loyal'
END as customer_segment
from customer)

select customer_segment,count(*) as Number_of_customers
from total_purchased 
group by customer_segment

-- Q8. What are the top 3 most purchased products within each category? 
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased)

select item_rank,category,item_purchased,total_orders from item_counts
where item_rank<=3

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as previous_buyer from customer
where previous_purchases>=5 
group by subscription_status

-- Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc




